Execution config factory test (#41)
* create validation test

* create tests

* Merge branch 'refactor_to_run_from_command_line' into execution_config_factory_test

* modify the tests

* Merge branch 'execution_config_factory_test' of https://github.com/aliz-ai/jarvis into execution_config_factory_test

* Merge remote-tracking branch 'origin/refactor_to_run_from_command_line' into execution_config_factory_test

* Merge branch 'master' into execution_config_factory_test

* Merge branch 'master' of https://github.com/aliz-ai/jarvis into execution_config_factory_test

* Merge branch 'execution_config_factory_test' of https://github.com/aliz-ai/jarvis into execution_config_factory_test

* edit execution action tests

* edit execution action tests

* edit execution action tests

* edit execution action tests

* edit execution action config factory tests

* edit execution action config factory tests

* edit execution action config factory tests

* PR CR

* PR CR

* Pinning proper GH action version

Error: On 2022-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name.

We strongly advise updating your GitHub Action YAML from:
    uses: 'google-github-actions/setup-gcloud@master'
to:
    uses: 'google-github-actions/setup-gcloud@v0'

* edit execution action config factory tests

* Merge branch 'execution_config_factory_test' of https://github.com/aliz-ai/jarvis into execution_config_factory_test

* refactor execution action config factory

* refactor execution action config factory

* Enriched unit test contexts with contextId also replaced path comparison with canonical path comparison

* Added required checks to ExecutionActionConfigFactory

* Merge branch 'master' into execution_config_factory_test

Conflicts:
	src/main/java/ai/aliz/jarvis/context/JarvisContextLoader.java
	src/test/java/ai/aliz/jarvis/testconfig/TestInitActionConfigFactory.java

* Fixed packages

* Merge branch 'master' into execution_config_factory_test

* Merge branch 'master' into execution_config_factory_test